# GET http://localhost:9000/api/v1/products HTTP/1.1

#GET http://localhost:9000/api/v1/products/16 HTTP/1.1

POST http://localhost:9000/api/v1/products
Content-Type: 'application/json'

{
    "price": 500,
    "title": "My new car"
}